# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/protoconf/protoconf-xds/pkg/build.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goarch: "386"
      - goos: windows
        goarch: arm64
    main: ./cmd/protoconf-xds
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - # Name template of the recipe
    # Default to project name
    name: protoconf-xds

    repository:
      owner: protoconf
      name: homebrew-tap

      token: "{{ .Env.DEPLOY_GITHUB_TOKEN }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com

    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://docs.protoconf.sh/"

    # Template of your app's description.
    # Default is empty.
    description: "Envoy XDS integration for protoconf"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"
dockers:
  - id: protoconf-docker-amd64
    image_templates:
      - "protoconf/protoconf-xds:latest"
      - "protoconf/protoconf-xds:{{ .Tag }}"
      - "protoconf/protoconf-xds:v{{ .Major }}"
      - "protoconf/protoconf-xds:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/protoconf/protoconf-xds:latest"
      - "ghcr.io/protoconf/protoconf-xds:{{ .Tag }}"
      - "ghcr.io/protoconf/protoconf-xds:{{ .Tag }}-amd64"
      - "ghcr.io/protoconf/protoconf-xds:{{ .Major }}"
      - "ghcr.io/protoconf/protoconf-xds:{{ .Major }}.{{ .Minor }}"
    use: buildx
    dockerfile: build/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/protoconf/protoconf-xds"
      - "--label=org.opencontainers.image.license=MIT"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--platform=linux/amd64"
  - id: protoconf-docker-arm64
    image_templates:
      - "protoconf/protoconf-xds:latest"
      - "protoconf/protoconf-xds:{{ .Tag }}"
      - "protoconf/protoconf-xds:v{{ .Major }}"
      - "protoconf/protoconf-xds:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/protoconf/protoconf-xds:latest"
      - "ghcr.io/protoconf/protoconf-xds:{{ .Tag }}"
      - "ghcr.io/protoconf/protoconf-xds:{{ .Tag }}-arm64"
      - "ghcr.io/protoconf/protoconf-xds:{{ .Major }}"
      - "ghcr.io/protoconf/protoconf-xds:{{ .Major }}.{{ .Minor }}"
    use: buildx
    dockerfile: build/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/protoconf/protoconf-xds"
      - "--label=org.opencontainers.image.license=MIT"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--platform=linux/arm64"
    goarch: arm64
docker_manifests:
  - name_template: "ghcr.io/protoconf/protoconf-xds:{{ .Tag }}"
    image_templates:
      - "ghcr.io/protoconf/protoconf-xds:{{ .Tag }}-amd64"
      - "ghcr.io/protoconf/protoconf-xds:{{ .Tag }}-arm64"